spring:
  application:
    name: lv2-final-mission
  jpa:
    open-in-view: false
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


